#spring.application.name=auths
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:eRHTHpstAlMuZsciOxmWLKSFoAeLXqaM@roundhouse.proxy.rlwy.net:57808/railway
    username: root
    password: eRHTHpstAlMuZsciOxmWLKSFoAeLXqaM
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: armadillo-01.rmq.cloudamqp.com
    port: 5672
    username: nrasswdt
    password: ing0r9kuLADKvud5LxyJ-1XH80E5zr4s
    virtual-host: nrasswdt