#spring.application.name=files
server:
  port: 8082
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
cloudinary:
  cloud_name: dwt8nm72d
  api_key: 118398793585282
  api_secret: VPqOIM8CNQEVMAj6P_vCw5jl8sQ