#spring.application.name=order
server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:eRHTHpstAlMuZsciOxmWLKSFoAeLXqaM@roundhouse.proxy.rlwy.net:57808/railway
    username: root
    password: eRHTHpstAlMuZsciOxmWLKSFoAeLXqaM
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  vnp:
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: https://tcake.vercel.app/checkout/status
    tmnCode: 7BT3E68M
    secretKey: OD4UZL909QTOYAF2MJ3FBMT8X0A9VV07
    apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  appService:
    product: https://product-service-production-f217.up.railway.app/v1/api
    auth: https://auth-service-production-58c5.up.railway.app/v1/api/auth

